public with sharing class SQL {

    public static String OPERATOR_AND = 'AND';
    public static String OPERATOR_OR = 'OR';
    public static String OPERATOR_LIKE = 'LIKE';
    public static String OPERATOR_EQUALS = '=';
    public static String CONDITION_GROUP_START = '(';
    public static String CONDITION_GROUP_END = ')';
    public static String FIELD_SEPERATOR = ',';
    public static String TOKEN_SEPERATOR = ' ';

    public SQL() {

    }
}
