public with sharing class SQL {

    public static String OPERATOR_AND = 'AND';
    
    public static String OPERATOR_OR = 'OR';
    
    public static String OPERATOR_LIKE = 'LIKE';
    
    public static String OPERATOR_EQUALS = '=';
    
    
    // OP_AND, OP_OR, OP_LIKE, OP_EQ, OP_NEQ, OP_GT, OP_LT, OP_LTE, OP_GTE
    public static String OP_NEQ = '!=';
    
    public static String CONDITION_GROUP_START = '(';
    
    public static String CONDITION_GROUP_END = ')';
    
    public static String FIELD_SEPARATOR = ',';
    
    public static String TOKEN_SEPARATOR = ' ';

		public static final String ORDER_BY_ASC = 'ASC';
		
		public static final String ORDER_BY_DESC = 'DESC';

    public SQL() {

    }
}
